version: 2.1

executors:
  android-executor:
    docker:
      - image: cimg/android:2024.01-browsers  # Updated to include more tools
    environment:
      ANDROID_HOME: /home/circleci/android-sdk
      ANDROID_SDK_ROOT: /home/circleci/android-sdk
      PATH: /home/circleci/android-sdk/cmdline-tools/latest/bin:/home/circleci/android-sdk/platform-tools:${PATH}

jobs:
  setup-environment:
    executor: android-executor
    steps:
      - checkout
      - run:
          name: Debug environment
          command: |
            which sdkmanager
            echo $ANDROID_HOME
            echo $PATH
      - run:
          name: Accept Licenses
          command: |
            echo y | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
      - run:
          name: Install Android SDK components
          command: |
            $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
              "platform-tools" \
              "platforms;android-33" \
              "build-tools;33.0.2" \
              "system-images;android-33;google_apis;x86_64" \
              "emulator"
      - run:
          name: Create AVD
          command: |
            $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd \
              -n testAVD \
              -k "system-images;android-33;google_apis;x86_64" \
              --device "pixel" \
              --force
      - persist_to_workspace:
          root: ~/
          paths:
            - .android
            - android-sdk

  run-tests:
    executor: android-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: Install Node.js and npm
          command: |
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - run:
          name: Start AVD and Appium
          command: |
            nohup $ANDROID_HOME/emulator/emulator -avd testAVD -no-audio -no-window &
            $ANDROID_HOME/platform-tools/adb wait-for-device
            $ANDROID_HOME/platform-tools/adb shell input keyevent 82
            npm install -g appium
            appium --log-level error &
      - run:
          name: Run Appium Tests
          command: mvn clean test
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/surefire-reports

workflows:
  version: 2
  appium-tests:
    jobs:
      - setup-environment
      - run-tests:
          requires:
            - setup-environment