version: 2.1

executors:
  android-executor:
    docker:
      - image: cimg/android:2024.01
    environment:
      ANDROID_HOME: /home/circleci/android-sdk
      ANDROID_SDK_ROOT: /home/circleci/android-sdk
      PATH: /home/circleci/android-sdk/cmdline-tools/latest/bin:/home/circleci/android-sdk/platform-tools:${PATH}

jobs:
  setup-environment:
    executor: android-executor
    steps:
      - checkout
      - run:
          name: Install required packages
          command: |
            sudo apt-get update
            sudo apt-get install -y bash curl wget unzip
      - run:
          name: Setup Android SDK
          command: |
            mkdir -p ${ANDROID_HOME}/cmdline-tools
            wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
            unzip commandlinetools-linux-9477386_latest.zip
            mv cmdline-tools ${ANDROID_HOME}/cmdline-tools/latest
      - run:
          name: Install Android SDK components
          command: |
            yes | ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --licenses
            ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager \
              "platform-tools" \
              "platforms;android-33" \
              "build-tools;33.0.2" \
              "system-images;android-33;google_apis;x86_64" \
              "emulator"
      - run:
          name: Create AVD
          command: |
            ${ANDROID_HOME}/cmdline-tools/latest/bin/avdmanager create avd \
              -n testAVD \
              -k "system-images;android-33;google_apis;x86_64" \
              --device "pixel" \
              --force
      - persist_to_workspace:
          root: ~/
          paths:
            - .android
            - android-sdk

  run-tests:
    executor: android-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: Start AVD and Appium
          command: |
            nohup emulator -avd testAVD -no-audio -no-window &
            adb wait-for-device
            adb shell input keyevent 82
            npm install -g appium
            appium --log-level error &
      - run:
          name: Run Appium Tests
          command: mvn clean test
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/surefire-reports

workflows:
  version: 2
  appium-tests:
    jobs:
      - setup-environment
      - run-tests:
          requires:
            - setup-environment
