version: 2.1

executors:
  android-executor:
    docker:
      - image: circleci/android:2021.10.2
    environment:
      ANDROID_HOME: /opt/android/sdk
      ANDROID_SDK_ROOT: /opt/android/sdk
      PATH: /opt/android/sdk/cmdline-tools/latest/bin:/opt/android/sdk/platform-tools:/opt/android/sdk/tools/bin:${PATH}

jobs:
  setup-environment:
    executor: android-executor
    steps:
      - checkout
      - run:
          name: Install packages
          command: |
            sudo apt-get update
            sudo apt-get install -y bash
      - run:
          name: Debug environment
          command: |
            echo $ANDROID_HOME
            echo $PATH
            which sh
            which bash
      - run:
          name: Accept Android SDK licenses
          command: |
            mkdir -p $ANDROID_HOME/licenses
            echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > $ANDROID_HOME/licenses/android-sdk-license
      - run:
          name: Install Android SDK components
          command: |
            sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2" "system-images;android-33;google_apis;x86_64" "emulator"
      - run:
          name: Create AVD
          command: |
            echo "no" | avdmanager create avd -n testAVD -k "system-images;android-33;google_apis;x86_64" --device "pixel" --force
      - persist_to_workspace:
          root: ~/
          paths:
            - .android
            - android-sdk

  run-tests:
    executor: android-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: Start AVD and Appium
          command: |
            nohup emulator -avd testAVD -no-audio -no-window &
            adb wait-for-device
            adb shell input keyevent 82
            npm install -g appium
            appium --log-level error &
      - run:
          name: Run Appium Tests
          command: mvn clean test
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/surefire-reports

workflows:
  version: 2
  appium-tests:
    jobs:
      - setup-environment
      - run-tests:
          requires:
            - setup-environment
