version: 2.1

executors:
  java-executor:
    docker:
      - image: circleci/openjdk:11
    working_directory: ~/repo
    environment:
      ANDROID_HOME: /opt/android-sdk
      PATH: "/home/circleci/apache-maven-3.8.4/bin:$PATH:/opt/android-sdk/cmdline-tools/bin:$PATH"
      JAVA_HOME: "/usr/lib/jvm/java-11-openjdk-amd64"

jobs:
  setup:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run:
          name: Install Maven
          command: |
            curl -O https://archive.apache.org/dist/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.tar.gz
            tar -xzvf apache-maven-3.8.4-bin.tar.gz -C /home/circleci
            echo "export PATH=/home/circleci/apache-maven-3.8.4/bin:$PATH" >> ~/.bashrc
            source ~/.bashrc

      - run:
          name: Install Node.js and npm
          command: |
            curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get update
            sudo apt-get install -y nodejs
            sudo apt-get install -y npm
            sudo apt-get install -y node-gyp
            node -v
            npm -v
            sudo npm install -g npm@latest

      - run:
          name: Install Appium and Android SDK
          command: |
            npm install -g appium
            wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
            unzip commandlinetools-linux-7583922_latest.zip -d /opt/android-sdk
            yes | /opt/android-sdk/cmdline-tools/bin/sdkmanager --licenses
            /opt/android-sdk/cmdline-tools/bin/sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30"
            echo "export PATH=/opt/android-sdk/cmdline-tools/bin:$PATH" >> ~/.bashrc
            echo "export ANDROID_HOME=/opt/android-sdk" >> ~/.bashrc
            source ~/.bashrc

      - run:
          name: Verify Android SDK installation
          command: |
            echo $ANDROID_HOME
            ls /opt/android-sdk

  run-tests:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Install dependencies and run Appium tests with Maven
          command: |
            mvn clean install
            mvn test

workflows:
  version: 2
  test:
    jobs:
      - setup
      - run-tests:
          requires:
            - setup
