version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8  # You can choose an image suitable for your setup
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y software-properties-common
            echo "y" | sudo apt-add-repository ppa:openjdk-r/ppa  # Automatically confirm repository addition
            sudo apt-get update
            sudo apt-get install -y openjdk-11-jdk maven
            sudo apt-get install -y android-sdk
            sudo apt-get install -y dbus dbus-x11  # Install dbus and dbus-x11 to fix the connection issue
            sudo apt-get install -y curl  # For downloading nodejs

      - run:
          name: Install Node.js and npm
          command: |
            curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt-get install -y nodejs

      - run:
          name: Install Appium
          command: |
            sudo npm install -g appium

      - run:
          name: Run Appium tests with Maven
          command: |
            mvn clean install

workflows:
  version: 2
  build:
    jobs:
      - build
