name: CI for Appium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Install Maven
        run: |
          curl -O https://archive.apache.org/dist/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.tar.gz
          chmod +x apache-maven-3.8.4-bin.tar.gz
          tar -xvzf apache-maven-3.8.4-bin.tar.gz
          sudo mv apache-maven-3.8.4 /opt/maven
          echo "MAVEN_HOME=/opt/maven" >> $GITHUB_ENV
          echo "PATH=$MAVEN_HOME/bin:$PATH" >> $GITHUB_ENV

      - name: Verify Maven installation
        run: mvn -v

      - name: Install project dependencies
        run: mvn install

      - name: Run Appium tests
        run: mvn test
