version: 2.1

executors:
  java-executor:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo

jobs:
  setup:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: Install Maven
          command: |
            curl -O https://archive.apache.org/dist/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.tar.gz
            tar -xzvf apache-maven-3.8.4-bin.tar.gz -C /opt
            echo "export PATH=/opt/apache-maven-3.8.4/bin:$PATH" >> ~/.bashrc
            source ~/.bashrc
      - run:
          name: Install Appium and Android SDK
          command: |
            npm install -g appium
            wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
            unzip commandlinetools-linux-7583922_latest.zip -d /opt/android-sdk
            yes | /opt/android-sdk/cmdline-tools/bin/sdkmanager --licenses
            /opt/android-sdk/cmdline-tools/bin/sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30"
            # Fix potential path issues
            echo "export PATH=/opt/android-sdk/cmdline-tools/bin:$PATH" >> ~/.bashrc
            echo "export ANDROID_HOME=/opt/android-sdk" >> ~/.bashrc
            source ~/.bashrc
      - run:
          name: Verify Android SDK installation
          command: |
            echo $ANDROID_HOME
            ls /opt/android-sdk

  run-tests:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: Install dependencies and run Appium tests with Maven
          command: |
            curl -O https://archive.apache.org/dist/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.tar.gz
            tar -xzvf apache-maven-3.8.4-bin.tar.gz -C /opt
            echo "export PATH=/opt/apache-maven-3.8.4/bin:$PATH" >> ~/.bashrc
            source ~/.bashrc
            mvn clean install
            mvn test

workflows:
  version: 2
  test:
    jobs:
      - setup
      - run-tests:
          requires:
            - setup
