version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8  # You can choose an image suitable for your setup
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            # Update and upgrade packages with non-interactive mode
            sudo apt-get update -y
            DEBIAN_FRONTEND=noninteractive sudo apt-get upgrade -y || true
            # Remove potential lock files
            sudo rm -f /var/lib/apt/lists/lock
            sudo rm -f /var/cache/apt/archives/lock
            sudo rm -f /var/lib/dpkg/lock*
            sudo dpkg --configure -a
            sudo apt-get install -y software-properties-common
            echo "y" | sudo apt-add-repository ppa:openjdk-r/ppa  # Automatically confirm repository addition
            sudo apt-get update -y
            sudo apt-get install -y openjdk-11-jdk maven android-sdk dbus dbus-x11 curl libnode-dev

      - run:
          name: Install Node.js and npm (with fixes)
          command: |
            curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
            sudo apt-get install -y npm  # Ensure npm is installed

      - run:
          name: Install Appium
          command: |
            sudo npm install -g appium

      - run:
          name: Run Appium tests with Maven
          command: |
            mvn clean install

workflows:
  version: 2
  build:
    jobs:
      - build
