version: 2.1

executors:
  android-executor:
    docker:
      - image: cimg/android:2023.08
    environment:
      ANDROID_HOME: /opt/android
      ANDROID_SDK_ROOT: /opt/android
      PATH: /opt/android/cmdline-tools/latest/bin:$PATH

jobs:
  setup-environment:
    executor: android-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2" "system-images;android-33;google_apis;x86_64"
            sdkmanager --licenses
            echo "y" | sdkmanager --install emulator
            avdmanager create avd -n testAVD -k "system-images;android-33;google_apis;x86_64" --device "pixel"
      - persist_to_workspace:
          root: ~/
          paths:
            - .android

  run-tests:
    executor: android-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: Start AVD and Appium
          command: |
            nohup emulator -avd testAVD -no-audio -no-window &
            adb wait-for-device
            adb shell input keyevent 82
            npm install -g appium
            appium --log-level error &
      - run:
          name: Run Appium Tests
          command: mvn clean test
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/surefire-reports

workflows:
  version: 2
  appium-tests:
    jobs:
      - setup-environment
      - run-tests:
          requires:
            - setup-environment
