name: Android Appium Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [33]  # Android 13
        target: [google_apis]
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Appium
        run: |
          npm install -g appium@2.5.1
          appium driver install uiautomator2
          appium &

      - name: Cache AVD files
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: pixel_6
          cores: 2
          ram-size: 4096M
          disk-size: 8192M
          script: echo "Generated AVD snapshot for caching."

      - name: Run Appium Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: pixel_6
          cores: 2
          ram-size: 4096M
          disk-size: 8192M
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: |
            # Wait for ADB to detect the emulator
            max_retries=30
            counter=0
            until adb shell getprop sys.boot_completed 2>&1 | grep -q '1'; do
              if [ $counter -eq $max_retries ]; then
                echo "Error: Emulator didn't start within expected time"
                exit 1
              fi
              counter=$((counter + 1))
              echo "Waiting for emulator to start... ($counter/$max_retries)"
              sleep 10
            done

            # Verify ADB connection
            adb devices
            echo "Emulator is ready"
            
            # Additional device preparation
            adb shell settings put global window_animation_scale 0.0
            adb shell settings put global transition_animation_scale 0.0
            adb shell settings put global animator_duration_scale 0.0
            
            # Wait for device to be fully ready
            sleep 30
            
            # Run the actual tests
            mvn clean test -Pandroid

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            target/surefire-reports/
            target/screenshots/