name: Appium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: $HOME/Android/Sdk
      ANDROID_EMULATOR_WAIT_TIME_BEFORE_KILL: 60
      EMULATOR_TIMEOUT: 600  # 10 minutes timeout for emulator startup
      JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.14-7/x64
      JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.14-7/x64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Appium
        run: npm install -g appium

      - name: Start Appium Server
        run: appium --log appium.log &

      - name: Install Android SDK Command-line Tools
        run: |
          # Install the SDK tools
          mkdir -p $HOME/Android/Sdk/cmdline-tools
          cd $HOME/Android/Sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O commandlinetools.zip
          unzip commandlinetools.zip -d cmdline-tools
          rm commandlinetools.zip
          mv $HOME/Android/Sdk/cmdline-tools/cmdline-tools $HOME/Android/Sdk/cmdline-tools/latest
          yes | $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/Android/Sdk --update
          yes | $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/Android/Sdk "system-images;android-30;google_apis;x86_64"
          yes | $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/Android/Sdk --install "platform-tools"

      - name: Install Android Emulator System Image
        run: yes | $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/Android/Sdk "system-images;android-30;google_apis;x86_64"

      - name: List available AVD devices
        run: $HOME/Android/Sdk/cmdline-tools/latest/bin/avdmanager list device

      - name: Create Android Emulator (AVD)
        run: |
          echo "Creating AVD..."
          $HOME/Android/Sdk/cmdline-tools/latest/bin/avdmanager create avd --force -n test-emulator --abi google_apis/x86_64 --package "system-images;android-30;google_apis;x86_64" --device "Pixel 5"

      - name: Start Android Emulator
        run: |
          echo "Starting Android Emulator..."
          nohup $HOME/Android/Sdk/emulator/emulator -avd test-emulator -noaudio -no-window -gpu swiftshader_indirect -port 5554 &
          echo "Waiting for emulator to boot up..."
          adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'
          echo "Emulator is ready!"

      - name: Install Maven dependencies
        run: mvn clean install

      - name: Run Appium tests
        run: mvn test

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: target/surefire-reports/

      - name: Clean up Android Emulator
        run: |
          echo "Shutting down emulator..."
          adb -s emulator-5554 emu kill || echo "Graceful shutdown failed"
          adb -s emulator-5554 emu kill || adb -s emulator-5554 shell reboot -p || adb -s emulator-5554 emu kill
