name: Java Appium Maven CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [30]
        target: [default]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install and Run Appium Server
      run: |
        npm install -g appium@v1.20.2
        appium -v
        appium &>/dev/null &
    - name: Start Emulator
      uses: reactivecircus/android-emulator-runner@v1
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86_64
        profile: Nexus 6
        headless: true
        disable-animations: true
        script: echo "Emulator started successfully"
    - name: Wait for Emulator to be Ready
      run: |
        echo "Waiting for emulator to be ready..."
        boot_completed=""
        timeout=600
        elapsed=0
        while [[ "$boot_completed" != "1" && $elapsed -lt $timeout ]]; do
          sleep 5
          boot_completed=$(adb -e shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')
          echo "Boot status: $boot_completed"
          elapsed=$((elapsed + 5))
        done
        if [[ "$boot_completed" != "1" ]]; then
          echo "Emulator failed to boot in time"
          exit 1
        fi
        echo "Emulator is ready!"
        adb devices
    - name: Run Appium Tests
      run: mvn clean test
