on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [30]
        target: [google_apis]

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install and Run Appium Server
      run: |
        npm install -g appium
        appium -v
        appium &>/dev/null &

    - name: Run Emulator
      uses: reactivecircus/android-emulator-runner@v1
      with:
        api-level: 30
        target: google_apis
        arch: x86_64
        profile: Nexus 6
        headless: true
        disable-animations: true
        emulator-options: "-no-boot-anim -noaudio -camera-back none"

    - name: Wait for Emulator to Boot
      run: |
        adb wait-for-device shell getprop sys.boot_completed
        sleep 30
        adb devices

    - name: Debug Emulator State
      run: |
        adb devices
        adb shell getprop sys.boot_completed || true

    - name: Run Appium Tests
      run: mvn clean test
