name: Appium CI

on: [push]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [25]
        target: [default]
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        distribution: 'temurin'
        cache: maven

    - name: Install Maven
      run: |
        brew install maven
        mvn -version

    - name: Install Appium
      run: npm install -g appium

    - name: Start Appium Server
      run: appium --log appium.log --base-path /wd/hub &

    - name: Run Appium Tests
      uses: reactivecircus/android-emulator-runner@v1
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86_64
        profile: Nexus 6
        script: mvn clean test
